version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=eats
      - POSTGRES_PORT=5433
      - POSTGRES_USER=eats-admin
      - POSTGRES_PASSWORD=eats1234!
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app
    command: npm run server
    depends_on:
      - db
